# Generated by Django 4.2.6 on 2023-10-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=30)),
                ("result_count", models.IntegerField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
