# Generated by Django 4.2.6 on 2023-10-24 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0005_alter_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 16, 43, 37, 409179, tzinfo=datetime.timezone.utc)),
        ),
    ]
