# Generated by Django 4.2.6 on 2023-10-24 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0007_alter_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 16, 44, 43, 263314, tzinfo=datetime.timezone.utc)),
        ),
    ]
