# Generated by Django 4.2.6 on 2023-10-24 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0008_alter_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
