# Generated by Django 4.2.6 on 2023-10-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0010_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='country',
        ),
    ]
